### ISSUE TITLE
 7-zip is not installed on this machine.

### ISSUE THREAD

**Issue by brunobertechini** [TotalALM/VSTS-Tasks#14]
This error occurs with a brand new task added for new release definition.

Bruno

**Comment by brunobertechini** [comment]
Executing the powershell script: C:\a\_tasks\7zExtract_b58262a2-2f04-4d7a-a9f7-a33f38dac76c\1.0.2\7zE.ps1

2016-09-22T23:11:54.7334618Z ##[error]System.Management.Automation.RuntimeException: 7-zip is not installed on this machine. ---> System.Management.Automation.RuntimeException: 7-zip is not installed on this machine.

2016-09-22T23:11:54.7334618Z    --- End of inner exception stack trace ---
 
2016-09-22T23:11:54.7334618Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
 
2016-09-22T23:11:54.7334618Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
 
2016-09-22T23:11:54.7334618Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
 
2016-09-22T23:11:54.7334618Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
 
2016-09-22T23:11:54.7334618Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
 
2016-09-22T23:11:54.7334618Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
 
2016-09-22T23:11:54.7404612Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by brunobertechini** [comment]
Any update?

**Comment by KevinDMack** [comment]
I'm trying to understand the issue your running into, cause looking at the exception you identified the task is actually behaving as designed.  The task leverages the installed instance of 7-zip on the server and in the absence of that installation will through the exception to inform you that it needs to be installed.  Are you running this on a server you have the ability to install 7-zip on? If not, or if this is a hosted agent, I would recommend running the chocolatey task in the collection to install 7-zip using this package https://chocolatey.org/packages/7zip.install.

**Comment by KevinDMack** [comment]
Did you have any update, were you able to leverage this option?
