### ISSUE TITLE
Random CommandNotFoundException

### ISSUE THREAD

**Issue by Franklin89** [TotalALM/VSTS-Tasks#23]
Sometimes out of the blue I get the following exception:
Running the task a second time works fine...
Any idea what the issue is?

`2017-02-22T17:02:39.4529609Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Get-LocalizedString' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2017-02-22T17:02:39.4539610Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
2017-02-22T17:02:39.4539610Z ##[error]   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2017-02-22T17:02:39.4549611Z ##[error]   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2017-02-22T17:02:39.4549611Z ##[error]   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2017-02-22T17:02:39.4549611Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2017-02-22T17:02:39.4559612Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2017-02-22T17:02:39.4559612Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-02-22T17:02:39.4559612Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)`

**Comment by KevinDMack** [comment]
Thanks for the complete description, will take a look to see if we can replicate it.

**Comment by Franklin89** [comment]
Before you put tons of work in it check out the pr #9 seems to ne the fix :-)
