### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by GirijeshD** [TotalALM/VSTS-Tasks#32]
Hi.. I am using a single DLL to File's.. & getting the exception:

2018-02-13T07:47:44.1885150Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is an empty string.
2018-02-13T07:47:44.1885657Z    at System.Management.Automation.ParameterBinderController.BindPositionalParametersInSet(UInt32 validParameterSets, Dictionary`2 nextPositionalParameters, CommandParameterInternal argument, ParameterBindingFlags flags, ParameterBindingException& bindingException)
2018-02-13T07:47:44.1885925Z    at System.Management.Automation.ParameterBinderController.BindPositionalParameters(Collection`1 unboundArguments, UInt32 validParameterSets, UInt32 defaultParameterSet, ParameterBindingException& outgoingBindingException)
2018-02-13T07:47:44.1886136Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
2018-02-13T07:47:44.1886299Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
2018-02-13T07:47:44.1886471Z    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
2018-02-13T07:47:44.1887398Z    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
2018-02-13T07:47:44.1887530Z    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
2018-02-13T07:47:44.1887676Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2018-02-13T07:47:44.1887796Z --- End of stack trace from previous location where exception was thrown ---
2018-02-13T07:47:44.1887909Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-02-13T07:47:44.1888041Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2018-02-13T07:47:44.1888209Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2018-02-13T07:47:44.1888412Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2018-02-13T07:47:44.1888542Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-02-13T07:47:44.1888690Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-02-13T07:47:44.5601561Z ##[error]System.Management.Automation.RuntimeException: Fx Cop not installed ---> System.Management.Automation.RuntimeException: Fx Cop not installed
2018-02-13T07:47:44.5602409Z    --- End of inner exception stack trace ---
2018-02-13T07:47:44.5602796Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-02-13T07:47:44.5603024Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-02-13T07:47:44.5604831Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-02-13T07:47:44.5605148Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-13T07:47:44.5605430Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-02-13T07:47:44.5605672Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-02-13T07:47:44.6136786Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by KevinDMack** [comment]
Can you provide any of the values you are using when trying to execute this.  It would indicate that you are not passing the working directory or the location of the files being tokenized.
